server:
  port: { SERVER_PORT }

spring:
  application:
    name: Tasker API
  datasource:
    url: ${DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update